name: Demo Jest

on: [pull_request]

jobs:
  demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    environment: env
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test
      - name: set commit status
        run: |
          echo "LALALA=PO" >> .env
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env
          node bin/set-github-status --github-repository=${{ github.repository }} --github-sha=${{ github.event.after }}